### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by fatpelt** [nathanielc/morgoth#50]
panic: assignment to entry in nil map
 
goroutine 9 [running]:
panic(0x569c20, 0xc82046a390)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.(*Handler).EndBatch(0xc820064120, 0xc82044e800, 0x0, 0x0)
        /home/administrator/go/src/github.com/nathanielc/morgoth/cmd/morgoth/main.go:340 +0x356
github.com/nathanielc/morgoth/vendor/github.com/influxdata/kapacitor/udf/agent.(*Agent).readLoop(0xc820052150, 0x0, 0x0)
        /home/administrator/go/src/github.com/nathanielc/morgoth/vendor/github.com/influxdata/kapacitor/udf/agent/agent.go:209 +0x4fe
github.com/nathanielc/morgoth/vendor/github.com/influxdata/kapacitor/udf/agent.(*Agent).Start.func1(0xc820052150)
        /home/administrator/go/src/github.com/nathanielc/morgoth/vendor/github.com/influxdata/kapacitor/udf/agent/agent.go:89 +0x6b
created by github.com/nathanielc/morgoth/vendor/github.com/influxdata/kapacitor/udf/agent.(*Agent).Start
        /home/administrator/go/src/github.com/nathanielc/morgoth/vendor/github.com/influxdata/kapacitor/udf/agent/agent.go:98 +0x1bb
 
------
ID: dev-morgoth
Error:
Template:
Type: stream
Status: enabled
Executing: true
Created: 29 Jun 17 22:44 UTC
Modified: 10 Jul 17 23:33 UTC
LastEnabled: 10 Jul 17 23:33 UTC
Databases Retention Policies: ["stats"."autogen"]
TICKscript:
stream
    |from()
        .measurement('traf')
        .groupBy(*)
    |window()
        .periodCount(60)
        .everyCount(60)
    @morgoth()
        .field('traffic_out')
        .scoreField('anomalyScore')
        .sigma(3.5)
    |alert()
        .details('error')
        .crit(lambda: "anomalyScore" > 0.9)
        .log('/tmp/dev-morgoth-alerts.log')

**Comment by fatpelt** [comment]
apologies, i should provide a couple more data points.

OS: ubuntu 16.04
Go version: go1.6.2
Influx db on localhost: 1.2.4-1
kapacitor on localhost: 1.3.1-1
morgoth version: HEAD
data rate: average between 750 and 800 data points per second
