### ISSUE TITLE
error when trying to start Kapacitor with and without Morgoth

### ISSUE THREAD

**Issue by CJosePhD** [nathanielc/morgoth#63]
Installed go (v1.92) kapaccitor (v1.4) influxdb(v1.3.8) getting error on kapacitor startup
ERROR:
s=2018-03-28T09:49:59.141-04:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="invalid character '<' looking for beginning of value"

ts=2018-03-28T09:49:59.675-04:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="invalid character '<' looking for beginning of value"

ts=2018-03-28T09:50:00.703-04:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="invalid character '<' looking for beginning of value"

ts=2018-03-28T09:50:02.077-04:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="invalid character '<' looking for beginning of value"

**Comment by edbernier** [comment]
I also saw an error when trying to use Morgoth with the 1.5.1 version of InfluxDB and Kapacitor V1.4.1.  What I added to the kapacitor.conf file were the following lines:
[udf.functions]
[udf.functions.morgoth]
  prog = "/home/ubuntu/go_workspace/bin/morgoth"
  timeout = "10s"

The error I see when starting is as follows:
ts=2018-03-28T15:36:54.442Z lvl=info msg="UDF log" service=udf text="2018/03/28 15:36:54 I! Starting agent using STDIN/STDOUT"
ts=2018-03-28T15:36:54.443Z lvl=info msg="UDF log" service=udf text="2018/03/28 15:36:54 I! Stopping"
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text="panic: close of closed channel"
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text=
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text="goroutine 1 [running]:"
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text="panic(0x789fc0, 0xc82000ba80)"
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text="\t/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6"
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text=main.(*Handler).Stop(0xc8200fc000)
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text="\t/home/ubuntu/go_workspace/src/github.com/nathanielc/morgoth/cmd/morgoth/main.go:501 +0x29"
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text=main.main()
ts=2018-03-28T15:36:54.445Z lvl=info msg="UDF log" service=udf text="\t/home/ubuntu/go_workspace/src/github.com/nathanielc/morgoth/cmd/morgoth/main.go:114 +0xa35"

**Comment by ganeshdudwadkar** [comment]
I faced this issue when I setup the http proxy due to which it was unable to connect to db
